"""Add:saved_notes and follows table and customized foreign key relations

Revision ID: a2da25e4dff1
Revises: 4a546d6ced75
Create Date: 2026-02-08 17:22:06.829909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2da25e4dff1'
down_revision: Union[str, Sequence[str], None] = '4a546d6ced75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follow_id', sa.UUID(), nullable=False),
    sa.Column('follower_user_id', sa.UUID(), nullable=False),
    sa.Column('followed_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follow_id')
    )
    op.create_index(op.f('ix_follows_created_at'), 'follows', ['created_at'], unique=False)
    op.create_index(op.f('ix_follows_follow_id'), 'follows', ['follow_id'], unique=False)
    op.create_index(op.f('ix_follows_followed_user_id'), 'follows', ['followed_user_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_user_id'), 'follows', ['follower_user_id'], unique=False)
    op.create_table('saved_notes',
    sa.Column('save_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('save_id')
    )
    op.create_index(op.f('ix_saved_notes_created_at'), 'saved_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_notes_note_id'), 'saved_notes', ['note_id'], unique=False)
    op.create_index(op.f('ix_saved_notes_save_id'), 'saved_notes', ['save_id'], unique=False)
    op.create_index(op.f('ix_saved_notes_user_id'), 'saved_notes', ['user_id'], unique=False)
    op.drop_constraint(op.f('notes_user_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_user_id_fkey'), 'notes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_saved_notes_user_id'), table_name='saved_notes')
    op.drop_index(op.f('ix_saved_notes_save_id'), table_name='saved_notes')
    op.drop_index(op.f('ix_saved_notes_note_id'), table_name='saved_notes')
    op.drop_index(op.f('ix_saved_notes_created_at'), table_name='saved_notes')
    op.drop_table('saved_notes')
    op.drop_index(op.f('ix_follows_follower_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_followed_user_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follow_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_created_at'), table_name='follows')
    op.drop_table('follows')
    # ### end Alembic commands ###
